language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip
env:
  - PATH=/home/travis/gopath/bin:$PATH GR_VERSION=1.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - go get github.com/msteinert/pam 

script: go build -v -tags "pam"   

after_success:
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/codeskyblue/gorelease/master/scripts/build-pack.sh)" args0 "windows linux darwin"
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/codeskyblue/gorelease/master/scripts/upload-qiniu.sh)"
